### ISSUE TITLE
Using lodash & ampersand

### ISSUE THREAD

**Issue by mhuggins** [brentertz/backbone-route-control#1]
Hello good sir :smile:

I'm just leaving a note here, and it's likely something I'll spend time looking at, but I'd like to use this for a project that's using lodash (instead of underscore) and ampersand (instead of backbone).

The [backbone-route-control.js](https://github.com/brentertz/backbone-route-control/blob/master/backbone-route-control.js#L5) automatically requires underscore & backbone if `exports` is defined.  For my use case, `exports` will be defined, but neither of the require calls for underscore and backbone will succeed.

**Comment by brentertz** [comment]
Assuming that you are using Browserify, it sounds like you need a transform to swap out those dependencies.

Have a look at `aliasify`, `browserify-swap` or similar packages.

**Comment by mhuggins** [comment]
Looks like this will work for us.  Awesome, thanks!

**Comment by mhuggins** [comment]
We might still have an issue with the way it loads.  Backbone defines the router under the Backbone namespace, i.e.: `Backbone.Router`, while Ampersand defines `AmpersandRouter` (rather than namespacing as `Ampersand.Router`).  We'll look into a fix that solves both our needs and submit a PR. :)

**Comment by brentertz** [comment]
Worst case scenario, you can fork the repo and make the change yourself as Sam did here.  https://github.com/wookiehangover/backbone-route-control/commit/abc09ad2d3a9588944853cc980c77ec6a1a167da

I could alternatively add separate files or branches with different dependencies too.

I am really interested to see what you might find.

**Comment by mhuggins** [comment]
A third option would be to return the factory itself, such that you would require this via something like:

```
// lodash + ampersand use case
var _ = require('lodash');
var AmpersandRouter = require('ampersand-router');
var Router = require('backbone-route-control')(_, AmpersandRouter);

// underscore + backbone use case
var _ = require('underscore')
var Backbone = require('backbone')
var Router = require('backbone-route-control')(_, Backbone.Router);
```

You're much more familiar with approaches to JS app configuration & module inclusion than I am though, so I don't know if returning a factory (rather than the class) is a typical scenario.
